server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # 根路径 - 防止 / 报 404
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location ^~ /microAppStarview/assets/ {
        alias /usr/share/nginx/html/assets/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public";
        # 防止被其他规则 fallback
        try_files $uri = 404;
        
        types {
        text/css css;
        application/javascript js;
        image/png png;
        image/jpeg jpg;
        font/woff2 woff2;
        }
        
        default_type application/octet-stream;
    }

    location ^~ /microApp/starview/assets/ {
        alias /usr/share/nginx/html/assets/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public";
        # 防止被其他规则 fallback
        try_files $uri = 404;
        
        types {
        text/css css;
        application/javascript js;
        image/png png;
        image/jpeg jpg;
        font/woff2 woff2;
        }
        
        default_type application/octet-stream;
    }

    # favicon
    location /microApp/starview/favicon.ico {
        alias /usr/share/nginx/html/favicon.ico;
    }

    # 入口文件 (Vue / React 单页应用)
    location /microApp/starview/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}