// 映射接口省份 → 标准省份名称
export const provinceMap: Record<string, string> = {
  上海: "上海市",
  北京: "北京市",
  天津: "天津市",
  重庆: "重庆市",
  浙江: "浙江省",
  江苏: "江苏省",
  湖北: "湖北省",
  陕西: "陕西省",
  甘肃: "甘肃省",
  青海: "青海省",
  河南: "河南省",
  河北: "河北省",
  山西: "山西省",
  江西: "江西省",
  福建: "福建省",
  山东: "山东省",
  湖南: "湖南省",
  广东: "广东省",
  广西: "广西壮族自治区",
  安徽: "安徽省",
  辽宁: "辽宁省",
  吉林: "吉林省",
  黑龙江: "黑龙江省",
  海南: "海南省",
  四川: "四川省",
  贵州: "贵州省",
  云南: "云南省",
  西藏: "西藏自治区",
  内蒙古: "内蒙古自治区",
  宁夏: "宁夏回族自治区",
  新疆: "新疆维吾尔自治区",
  香港: "香港特别行政区",
  澳门: "澳门特别行政区",
  台湾: "台湾省",
  钓鱼岛: "钓鱼岛"
}


export const emptyProvinceData: Record<string, any> = {
  北京市: { avg: 0, detail: [] },
  天津市: { avg: 0, detail: [] },
  上海市: { avg: 0, detail: [] },
  重庆市: { avg: 0, detail: [] },
  河北省: { avg: 0, detail: [] },
  山西省: { avg: 0, detail: [] },
  辽宁省: { avg: 0, detail: [] },
  吉林省: { avg: 0, detail: [] },
  黑龙江省: { avg: 0, detail: [] },
  江苏省: { avg: 0, detail: [] },
  浙江省: { avg: 0, detail: [] },
  安徽省: { avg: 0, detail: [] },
  福建省: { avg: 0, detail: [] },
  江西省: { avg: 0, detail: [] },
  山东省: { avg: 0, detail: [] },
  河南省: { avg: 0, detail: [] },
  湖北省: { avg: 0, detail: [] },
  湖南省: { avg: 0, detail: [] },
  广东省: { avg: 0, detail: [] },
  广西壮族自治区: { avg: 0, detail: [] },
  海南省: { avg: 0, detail: [] },
  四川省: { avg: 0, detail: [] },
  贵州省: { avg: 0, detail: [] },
  云南省: { avg: 0, detail: [] },
  西藏自治区: { avg: 0, detail: [] },
  陕西省: { avg: 0, detail: [] },
  甘肃省: { avg: 0, detail: [] },
  内蒙古自治区: { avg: 0, detail: [] },
  青海省: { avg: 0, detail: [] },
  宁夏回族自治区: { avg: 0, detail: [] },
  新疆维吾尔自治区: { avg: 0, detail: [] },
  香港特别行政区: { avg: 0, detail: [] },
  澳门特别行政区: { avg: 0, detail: [] },
  台湾省: { avg: 0, detail: [] },
  钓鱼岛: { avg: 0, detail: [] }
}
